server:
  port: 9060
spring:
  application:
    name: api
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          application: api
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java?serverTimezone=GMT%2B8&characterEncoding=utf-8&userSSl=false
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: INFO
    org.springframework.web: INFO
###feign 默认关闭熔断，请看HystrixFeignConfiguration
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 60000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1